// import "./ting.scss";
export { default as Switch } from "./Switch/Switch.vue";
export { default as Button } from "./Button/Button.vue";
export { default as Tabs } from "./Tab/Tabs.vue";
export { default as Tab } from "./Tab/Tab.vue";
export { default as Dialog } from "./Dialog/Dialog.vue";
export { default as Input } from "./Input/Input.vue";
export { default as Password } from "./Input/Password.vue";
export { default as Row } from "./Grid/Row.vue";
export { default as Col } from "./Grid/Col.vue";
export { default as Layout } from "./Layout/Layout.vue";
export { default as Footer } from "./Layout/Footer.vue";
export { default as Header } from "./Layout/Header.vue";
export { default as Content } from "./Layout/Content.vue";
export { default as Sider } from "./Layout/Sider.vue";
export { default as Popover } from "./Popover/Popover.vue";

export { default as TingPlugin } from "./tools/plugin";
export { openDialog as openDialog } from "./Dialog/openDialog";
export { default as TingUI } from "./TingUI";
